### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by ian-cameron** [jodendaal/OpenAI.Net#73]
I'm using this library in my code and find it very helpful.  I have a lot of users and am interested in starting to send the [User or UserID](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids) optional parameter.  Do you have any plans to add this in the requests for images, chats, completions, or maybe an option in the client configuration?  Thank you.

**Comment by jodendaal** [comment]
Hi,

The property is already available to use on all those places mentioned. It is part of the request that can be set.

```csharp
 var messages = new List<Message>
            {
                Message.Create(ChatRoleType.User, "Say this is a test")
            };

            var request = new ChatCompletionRequest(messages)
            {
                Model = model,
                User = "User1"
            };
```

Using extension methods
```csharp
 var response = await OpenAIService.Chat.Get(messages,o => {
                o.MaxTokens = 1000;
                o.Model = model;
                o.User = "User1";
            });
```

**Comment by ian-cameron** [comment]
Excellent, Thank you!
