### ISSUE TITLE
Как сменить модель на GPT35Turbo?

### ISSUE THREAD

**Issue by MaKeSter333** [jodendaal/OpenAI.Net#75]

**Comment by jodendaal** [comment]
You can specify the model in various ways.

- If you are creating a Request object there is a property called Model on most reqeusts which you can set.
- You can set the model when calling the extension methods. See [OpenAIDefaults.TextCompletionModel](https://github.com/jodendaal/OpenAI.Net/blob/8047697a850013c8f4ca79eea29d9c1d2b878869/src/OpenAI.Net/Extensions/TextCompletionServiceExtensionMethods.cs#L25)
- You can set the default model by changing OpenAIDefaults.TextCompletionModel.

**Comment by Aspirin493** [comment]
chat = api.Chat.CreateConversation();
chat.RequestParameters.Model = "gpt-3.5-turbo-16k";
