### ISSUE TITLE
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by barbarossa426** [jodendaal/OpenAI.Net#77]
Problem: 
The issue I encountered is that when making HTTP requests using HttpClient, the request is being canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. This is causing disruptions in the functionality of our application, especially when dealing with long-running requests or slow network conditions.

Expected Behavior: 
In our application, we expect to be able to configure the HttpClient.Timeout to a value that is appropriate for our specific use case. However, when the timeout is reached, instead of canceling the request, we would like to have the option to handle it gracefully or take custom actions, such as logging, retrying, or displaying a user-friendly error message.

```CSHARP
try
{
    var response = await openAi.Chat.Get(messages, o =>
    {
        o.MaxTokens = 3000;
        o.TimeOut = 200  <=== Possible way to config timeout here
    });

    if ((response.IsSuccess) && (response.Result is not null))
    {
        foreach (var result in response.Result!.Choices)
        {
            output = await DeserializeMessageContent(result.Message.Content);
        }
    }
    else
    {
        throw new Exception(response.ErrorMessage);
    }
    return output;
}
catch (Exception ex)
{
    throw new GptProviderException("Faild to call OpenAI", ex);
}
```

**Comment by LyleRolleman-plst** [comment]
This can be done via the config
```
services.AddOpenAIServices(options =>
        {
            options.ApiKey = ...;
            options.ApiUrl = ...;
        }, httpBuilder => httpBuilder.ConfigureHttpClient(client =>
        {
            client.Timeout = TimeSpan.FromMinutes(10);
        }));
```

A few extra notes in the README would be nice in regards to configuration.

**Comment by barbarossa426** [comment]
@LyleRolleman-plst Thanks for the input!
