### ISSUE TITLE
DALL·E 3 API Support

### ISSUE THREAD

**Issue by ian-cameron** [jodendaal/OpenAI.Net#78]
The OpenAI Image Generation endpoint was recently updated with Model, Style and Quality parameters and the response has a new property for Revised Prompt: https://help.openai.com/en/articles/8555480-dall-e-3-api

Would like to use keep using this package with support for it.  PR coming for your consideration. Thank you!

**Comment by jodendaal** [comment]
Going to have a look at this now. I do also accept pull requests, so in future you are welcome to submit a PR for any new features.

**Comment by jodendaal** [comment]
This has been merged and is available in the latest nuget package v1.0.21. Thanks for your contribution.

https://www.nuget.org/packages/OpenAI.Net.Client

https://github.com/jodendaal/OpenAI.Net/releases/tag/v1.0.21
